### ISSUE TITLE
feature: Автоматическая перевыдача cookie

### ISSUE THREAD

**Issue by Zamelane** [Diary-SPO/vk-bot#17]
Если пользователь уже авторизирован в системе, но в первый раз открывает бота с момента запуска серверов, нужно попробовать перевыпустить ему токен с соответствующими сообщениями в чат
- [ ] Проверять время последней выдачи куки
- [ ] Автоматически перевыпускать куку, если прошло больше недели
- [ ] Добавить поле *lastTimeCookie* в таблицу ***diaryUser*** для отслеживания даты последнего изменения куки

**Comment by scffs** [comment]
Сделай, пожалуйста, нормальный таск-лист
Делается через `- [ ] Сделать что-то....`
