### ISSUE TITLE
Feature: уведомления об изменениях в дневнике

### ISSUE THREAD

**Issue by Zamelane** [Diary-SPO/vk-bot#23]
Уведомлять об изменениях в дневнике (оценки, перенос занятий на другое время, изменения в расписании)
- [ ] Добавить возможность выключать данную функцию в настройках
- [ ] Уведомлять о новых оценках (или если старая была изменена)
- [ ] Уведомлять, если расписание на текущий/следующий день было изменено (перенесли/добавили/убрали пары)

На обсуждение:
- [ ] Уведомлять, если подгруппы объединяют на каком-то занятии (у 1ой и 2ой подгруппы одинаковые кабинеты/преподаватели)
- [ ] Уведомлять за день о том, что нужно сдать ДЗ (если на предыдущей паре стояла пометка ДЗ, то перед следующей (в другой день/недели) нужно предупредить его сделать
- [ ] Предупреждать за день о проверочных/контрольных работах (может стоит уведомлять, если стоит required в поле ?)

**Comment by scffs** [comment]
>...может стоит уведомлять, если стоит required в поле ?
 
 Странный поинт, дело в том, что required очень много и преподы порой их странно ставаят, я бы не брал на себя такую ответственность. Мы уже отображаем Долг, будто бы больше ничего не надо
 
 > Уведомлять, если подгруппы объединяют на каком-то занятии
 Если преподы / учебный отдел не забывают менять кабинеты, то очень круто.
 
 Со всем другим абсолютно согласен
