### ISSUE TITLE
feature: получение расписания

### ISSUE THREAD

**Issue by scffs** [Diary-SPO/vk-bot#3]
UPD:

Что надо сделать в рамках таски:
- [ ] Расписание на неделю
- [ ] Выбор периода (через кнопкии + сообщение, например в формате `начало / конец` ->`10.10.2023 / 20.10.2023`
- [ ] Обрабатывать пустые пары
- [ ] Обрабатывать незаполненный кабинет (ДО) и другие незаполенные поля
- [ ] Отображать есть ли ДЗ на пару
- [ ] Есть ли Н / О / Д за пару (долг можно не отображать, надо обсудить)
- [ ] Ограничить максимальный период (например, пары максимум на месяц)
- [ ] Обработать если начальная дата > конечной и тд

Вопросы по таске тут / в чате
 
 UPD 09.10.23:
 
 - [ ] Кнопка запросить данные из базы
 - [ ] Кнопка обновить базу
 - [ ] Обработать падение сетевого города
 - [ ] Обновлять данные для групп/подгрупп + разобраться с подгруппами
 
Изначально показываем данные от сетевого города, базу юзаем при необходимости.

**Comment by Zamelane** [comment]
Т.к. это бот, то выводим по одному дню, так ведь? (Не всю неделю сразу)

**Comment by scffs** [comment]
> Т.к. это бот, то выводим по одному дню, так ведь? (Не всю неделю сразу)

В одном сообщении можно вывести все пары на неделю, просто разделим им через текст как-нибудь
```
Понедельник | 7.10.2023
пара
инфа

пара
инфа

пара
инфа

=====

Вторник| 8.10.2023
пара
инфа

пара
инфа

пара
инфа
```

Можно выводить пары и при клике на что-нибудь выводить подробную инфуо паре, как лучше?

**Comment by scffs** [comment]
Но в таком случае на месяц и даже на неделю будет очень сложно читать, подробную инфу о паре можно не указывать, а показывать при выборе определенной паре

Например, бот пишет "Для вывода подробной информации ввидите номер пары", если пары показаны за день. Если за неделю, то надо вводить и номер недели + пары
